// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgressoAcademico.Context;

#nullable disable

namespace ProgressoAcademico.Migrations
{
    [DbContext(typeof(ProgressoAcademicoDbContext))]
    [Migration("20260726234231_AdicionaUltimaMovimentacaoSolicitacao")]
    partial class AdicionaUltimaMovimentacaoSolicitacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProgressoAcademico.Models.Atividade", b =>
                {
                    b.Property<int>("AtividadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAvaliacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("OrigemCadastro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ParecerAvaliacao")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<decimal>("PontuacaoCalculada")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SolicitacaoProgressaoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SubTipoAtividadeId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAtividadeId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AtividadeId");

                    b.HasIndex("SolicitacaoProgressaoId");

                    b.HasIndex("SubTipoAtividadeId");

                    b.HasIndex("TipoAtividadeId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.AtividadeAdministrativa", b =>
                {
                    b.Property<int>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Unidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AtividadeId");

                    b.ToTable("AtividadesAdministrativas");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.AtividadeAvaliacaoRevisor", b =>
                {
                    b.Property<int>("AtividadeAvaliacaoRevisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Parecer")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SolicitacaoRevisorId")
                        .HasColumnType("int");

                    b.HasKey("AtividadeAvaliacaoRevisorId");

                    b.HasIndex("SolicitacaoRevisorId");

                    b.HasIndex("AtividadeId", "SolicitacaoRevisorId")
                        .IsUnique();

                    b.ToTable("AtividadesAvaliacoesRevisores");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.AtividadeEnsino", b =>
                {
                    b.Property<int>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("CodigoDisciplina")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("NomeDisciplina")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroAlunos")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AtividadeId");

                    b.ToTable("AtividadesEnsino");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.AtividadeExtensao", b =>
                {
                    b.Property<int>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<string>("CargaHoraria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Projeto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PublicoAlvo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AtividadeId");

                    b.ToTable("AtividadesExtensao");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.AtividadePesquisa", b =>
                {
                    b.Property<int>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<string>("ISSN_ISBN")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroAutores")
                        .HasColumnType("int");

                    b.Property<string>("TipoProducao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VeiculoPublicacao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AtividadeId");

                    b.ToTable("AtividadesPesquisa");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Comunicado", b =>
                {
                    b.Property<int>("ComunicadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CriadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Publicado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("varchar(350)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("ComunicadoId");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("Publicado", "DataPublicacao");

                    b.ToTable("Comunicados");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.ConteudoHome", b =>
                {
                    b.Property<int>("ConteudoHomeId")
                        .HasColumnType("int");

                    b.Property<int?>("AtualizadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("AvisoEscopo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoAdministrador")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<string>("DescricaoProfessor")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<string>("ItensDestaque")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)");

                    b.Property<string>("RecursosAdministrador")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)");

                    b.Property<string>("RecursosProfessor")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)");

                    b.Property<string>("ResumoProjeto")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)");

                    b.Property<string>("TituloDestaque")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("TituloPrincipal")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("varchar(220)");

                    b.HasKey("ConteudoHomeId");

                    b.HasIndex("AtualizadoPorUsuarioId");

                    b.ToTable("ConteudosHome");

                    b.HasData(
                        new
                        {
                            ConteudoHomeId = 1,
                            AvisoEscopo = "Sistema acadêmico funcional de apoio. Não substitui normas, sistemas oficiais ou atos administrativos da UFABC.",
                            DataAtualizacao = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            DescricaoAdministrador = "Coordena a análise das solicitações, atribui revisores, consulta pareceres e registra a decisão final.",
                            DescricaoProfessor = "Prepara e acompanha a própria solicitação, registra atividades e vincula documentos comprobatórios.",
                            ItensDestaque = "Solicitações e atividades centralizadas\nMúltiplos documentos por atividade\nRevisão técnica por professores avaliadores\nDecisão administrativa com parecer registrado",
                            RecursosAdministrador = "Atribui um ou mais revisores por solicitação\nConsulta pareceres técnicos e documentos\nSolicita ajustes quando necessário\nRegistra aprovação, rejeição ou encerramento",
                            RecursosProfessor = "Cria e acompanha solicitações\nCadastra atividades de ensino, pesquisa, extensão e gestão\nAnexa múltiplos comprovantes por atividade\nConsulta histórico, status e pendências",
                            ResumoProjeto = "Aplicação web funcional desenvolvida para organizar solicitações, atividades, documentos, revisões técnicas e decisão administrativa no processo de progressão acadêmica dos professores da Universidade Federal do ABC.",
                            TituloDestaque = "Fluxo estruturado para professor, revisor e administrador.",
                            TituloPrincipal = "Sistema integrado para apoio à progressão acadêmica docente."
                        });
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("Arquivo")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int?>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("application/octet-stream");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("OrigemDocumento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("ComprovatorioProfessor");

                    b.Property<int>("SolicitacaoProgressaoId")
                        .HasColumnType("int");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("DocumentoId");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("HashSha256");

                    b.HasIndex("SolicitacaoProgressaoId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Instituicao", b =>
                {
                    b.Property<int>("InstituicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("InstituicaoId");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Nivel", b =>
                {
                    b.Property<int>("NivelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("NivelId");

                    b.ToTable("Niveis");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SolicitacaoProgressao", b =>
                {
                    b.Property<int>("SolicitacaoProgressaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apelido")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("AtribuidoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtribuicaoRevisor")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataParecerRevisor")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRevisao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUltimaMovimentacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Multiprogressao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("NivelDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("NivelOrigemId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ParecerFinal")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ParecerRevisor")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("RevisadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("RevisorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("StatusSolicitacaoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoProgressoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SolicitacaoProgressaoId");

                    b.HasIndex("AtribuidoPorUsuarioId");

                    b.HasIndex("NivelDestinoId");

                    b.HasIndex("NivelOrigemId");

                    b.HasIndex("RevisadoPorUsuarioId");

                    b.HasIndex("RevisorUsuarioId");

                    b.HasIndex("StatusSolicitacaoId");

                    b.HasIndex("TipoProgressoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "StatusSolicitacaoId");

                    b.ToTable("SolicitacoesProgressao");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SolicitacaoRevisor", b =>
                {
                    b.Property<int>("SolicitacaoRevisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AtribuidoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAtribuicao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataParecer")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Parecer")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("RevisorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitacaoProgressaoId")
                        .HasColumnType("int");

                    b.Property<string>("StatusRevisao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("SolicitacaoRevisorId");

                    b.HasIndex("AtribuidoPorUsuarioId");

                    b.HasIndex("RevisorUsuarioId");

                    b.HasIndex("SolicitacaoProgressaoId", "RevisorUsuarioId")
                        .IsUnique();

                    b.ToTable("SolicitacoesRevisores");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.StatusSolicitacao", b =>
                {
                    b.Property<int>("StatusSolicitacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StatusSolicitacaoId");

                    b.ToTable("StatusSolicitacoes");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SubTipoAtividade", b =>
                {
                    b.Property<int>("SubtipoAtividadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("TipoAtividadeId")
                        .HasColumnType("int");

                    b.HasKey("SubtipoAtividadeId");

                    b.HasIndex("TipoAtividadeId");

                    b.ToTable("SubtiposAtividade");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.TipoAtividade", b =>
                {
                    b.Property<int>("TipoAtividadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("TipoAtividadeId");

                    b.ToTable("TiposAtividade");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.TipoProgresso", b =>
                {
                    b.Property<int>("TipoProgressoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TipoProgressoId");

                    b.ToTable("TiposProgresso");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.TipoVinculo", b =>
                {
                    b.Property<int>("TipoVinculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TipoVinculoId");

                    b.ToTable("TiposVinculo");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUltimoProgresso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PerfilAcesso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Professor");

                    b.Property<bool>("PodeRevisar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.UsuarioPerfil", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Apelido")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("FotoPerfilArquivo")
                        .HasColumnType("longblob");

                    b.Property<DateTime?>("FotoPerfilAtualizadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FotoPerfilContentType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UsuarioId");

                    b.ToTable("UsuariosPerfis");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.VinculoInstitucional", b =>
                {
                    b.Property<int>("VinculoInstitucionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataIngressoInstituicao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUltimaProgressao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InstituicaoId")
                        .HasColumnType("int");

                    b.Property<int>("NivelId")
                        .HasColumnType("int");

                    b.Property<int>("TipoVinculoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("VinculoInstitucionalId");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("NivelId");

                    b.HasIndex("TipoVinculoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("VinculosInstitucionais");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Atividade", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.SolicitacaoProgressao", "SolicitacaoProgressao")
                        .WithMany("Atividades")
                        .HasForeignKey("SolicitacaoProgressaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.SubTipoAtividade", "SubTipoAtividade")
                        .WithMany()
                        .HasForeignKey("SubTipoAtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.TipoAtividade", "TipoAtividade")
                        .WithMany()
                        .HasForeignKey("TipoAtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoProgressao");

                    b.Navigation("SubTipoAtividade");

                    b.Navigation("TipoAtividade");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.AtividadeAdministrativa", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithOne("AtividadeAdministrativa")
                        .HasForeignKey("ProgressoAcademico.Models.AtividadeAdministrativa", "AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.AtividadeAvaliacaoRevisor", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithMany("AvaliacoesRevisores")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.SolicitacaoRevisor", "SolicitacaoRevisor")
                        .WithMany("AvaliacoesAtividades")
                        .HasForeignKey("SolicitacaoRevisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("SolicitacaoRevisor");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.AtividadeEnsino", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithOne("AtividadeEnsino")
                        .HasForeignKey("ProgressoAcademico.Models.AtividadeEnsino", "AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.AtividadeExtensao", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithOne("AtividadeExtensao")
                        .HasForeignKey("ProgressoAcademico.Models.AtividadeExtensao", "AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.AtividadePesquisa", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithOne("AtividadePesquisa")
                        .HasForeignKey("ProgressoAcademico.Models.AtividadePesquisa", "AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Comunicado", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Usuario", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPorUsuario");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.ConteudoHome", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Usuario", "AtualizadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AtualizadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AtualizadoPorUsuario");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Documento", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithMany("Documentos")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProgressoAcademico.Models.SolicitacaoProgressao", "SolicitacaoProgressao")
                        .WithMany("Documentos")
                        .HasForeignKey("SolicitacaoProgressaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("SolicitacaoProgressao");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SolicitacaoProgressao", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Usuario", "AtribuidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AtribuidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProgressoAcademico.Models.Nivel", "NivelDestino")
                        .WithMany("SolicitacoesComoDestino")
                        .HasForeignKey("NivelDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.Nivel", "NivelOrigem")
                        .WithMany("SolicitacoesComoOrigem")
                        .HasForeignKey("NivelOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.Usuario", "RevisadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RevisadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProgressoAcademico.Models.Usuario", "RevisorUsuario")
                        .WithMany()
                        .HasForeignKey("RevisorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProgressoAcademico.Models.StatusSolicitacao", "StatusSolicitacao")
                        .WithMany("SolicitacaoProgressao")
                        .HasForeignKey("StatusSolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.TipoProgresso", "TipoProgresso")
                        .WithMany("SolicitacaoProgressao")
                        .HasForeignKey("TipoProgressoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.Usuario", "Usuario")
                        .WithMany("SolicitacaoProgressao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtribuidoPorUsuario");

                    b.Navigation("NivelDestino");

                    b.Navigation("NivelOrigem");

                    b.Navigation("RevisadoPorUsuario");

                    b.Navigation("RevisorUsuario");

                    b.Navigation("StatusSolicitacao");

                    b.Navigation("TipoProgresso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SolicitacaoRevisor", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Usuario", "AtribuidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AtribuidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProgressoAcademico.Models.Usuario", "RevisorUsuario")
                        .WithMany("RevisoesAtribuidas")
                        .HasForeignKey("RevisorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.SolicitacaoProgressao", "SolicitacaoProgressao")
                        .WithMany("Revisores")
                        .HasForeignKey("SolicitacaoProgressaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtribuidoPorUsuario");

                    b.Navigation("RevisorUsuario");

                    b.Navigation("SolicitacaoProgressao");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SubTipoAtividade", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.TipoAtividade", "TipoAtividade")
                        .WithMany("Subtipos")
                        .HasForeignKey("TipoAtividadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoAtividade");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.UsuarioPerfil", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Usuario", "Usuario")
                        .WithOne("UsuarioPerfil")
                        .HasForeignKey("ProgressoAcademico.Models.UsuarioPerfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.VinculoInstitucional", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Instituicao", "Instituicao")
                        .WithMany("Vinculos")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.Nivel", "Nivel")
                        .WithMany("VinculoInstitucionals")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.TipoVinculo", "TipoVinculo")
                        .WithMany("VinculoInstitucional")
                        .HasForeignKey("TipoVinculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.Usuario", "Usuario")
                        .WithMany("VinculosInstitucionais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituicao");

                    b.Navigation("Nivel");

                    b.Navigation("TipoVinculo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Atividade", b =>
                {
                    b.Navigation("AtividadeAdministrativa");

                    b.Navigation("AtividadeEnsino");

                    b.Navigation("AtividadeExtensao");

                    b.Navigation("AtividadePesquisa");

                    b.Navigation("AvaliacoesRevisores");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Instituicao", b =>
                {
                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Nivel", b =>
                {
                    b.Navigation("SolicitacoesComoDestino");

                    b.Navigation("SolicitacoesComoOrigem");

                    b.Navigation("VinculoInstitucionals");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SolicitacaoProgressao", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Documentos");

                    b.Navigation("Revisores");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SolicitacaoRevisor", b =>
                {
                    b.Navigation("AvaliacoesAtividades");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.StatusSolicitacao", b =>
                {
                    b.Navigation("SolicitacaoProgressao");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.TipoAtividade", b =>
                {
                    b.Navigation("Subtipos");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.TipoProgresso", b =>
                {
                    b.Navigation("SolicitacaoProgressao");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.TipoVinculo", b =>
                {
                    b.Navigation("VinculoInstitucional");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Usuario", b =>
                {
                    b.Navigation("RevisoesAtribuidas");

                    b.Navigation("SolicitacaoProgressao");

                    b.Navigation("UsuarioPerfil");

                    b.Navigation("VinculosInstitucionais");
                });
#pragma warning restore 612, 618
        }
    }
}
