// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgressoAcademico.Context;

#nullable disable

namespace ProgressoAcademico.Migrations
{
    [DbContext(typeof(ProgressoAcademicoDbContext))]
    [Migration("20260216021854_MassaDadosIniciaisParte1")]
    partial class MassaDadosIniciaisParte1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AtividadeAdministrativa", b =>
                {
                    b.Property<int>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Unidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AtividadeId");

                    b.ToTable("AtividadesAdministrativas");
                });

            modelBuilder.Entity("AtividadeEnsino", b =>
                {
                    b.Property<int>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("CodigoDisciplina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("NomeDisciplina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroAlunos")
                        .HasColumnType("int");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AtividadeId");

                    b.ToTable("AtividadesEnsino");
                });

            modelBuilder.Entity("AtividadeExtensao", b =>
                {
                    b.Property<int>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<string>("CargaHoraria")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Projeto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PublicoAlvo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AtividadeId");

                    b.ToTable("AtividadesExtensao");
                });

            modelBuilder.Entity("AtividadePesquisa", b =>
                {
                    b.Property<int>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<string>("ISSN_ISBN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroAutores")
                        .HasColumnType("int");

                    b.Property<string>("TipoProducao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VeiculoPublicacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AtividadeId");

                    b.ToTable("AtividadesPesquisa");
                });

            modelBuilder.Entity("Instituicao", b =>
                {
                    b.Property<int>("InstituicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("InstituicaoId");

                    b.ToTable("Instituicoes");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Atividade", b =>
                {
                    b.Property<int>("AtividadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PontuacaoCalculada")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("SolicitacaoProgressaoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SubTipoAtividadeId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAtividadeId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AtividadeId");

                    b.HasIndex("SolicitacaoProgressaoId");

                    b.HasIndex("SubTipoAtividadeId");

                    b.HasIndex("TipoAtividadeId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Documento", b =>
                {
                    b.Property<int>("DocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("Arquivo")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int?>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitacaoProgressaoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("DocumentoId");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("SolicitacaoProgressaoId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Nivel", b =>
                {
                    b.Property<int>("NivelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("NivelId");

                    b.ToTable("Niveis");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SolicitacaoProgressao", b =>
                {
                    b.Property<int>("SolicitacaoProgressaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NivelDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("NivelOrigemId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ParecerFinal")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("StatusSolicitacaoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoProgressoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SolicitacaoProgressaoId");

                    b.HasIndex("NivelDestinoId");

                    b.HasIndex("NivelOrigemId");

                    b.HasIndex("StatusSolicitacaoId");

                    b.HasIndex("TipoProgressoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitacoesProgressao");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.StatusSolicitacao", b =>
                {
                    b.Property<int>("StatusSolicitacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StatusSolicitacaoId");

                    b.ToTable("StatusSolicitacoes");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.TipoProgresso", b =>
                {
                    b.Property<int>("TipoProgressoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TipoProgressoId");

                    b.ToTable("TiposProgresso");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUltimoProgresso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.UsuarioPerfil", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UsuarioId");

                    b.ToTable("UsuariosPerfis");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.VinculoInstitucional", b =>
                {
                    b.Property<int>("VinculoInstitucionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataIngressoInstituicao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUltimaProgressao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InstituicaoId")
                        .HasColumnType("int");

                    b.Property<int>("NivelId")
                        .HasColumnType("int");

                    b.Property<int>("TipoVinculoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("VinculoInstitucionalId");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("NivelId");

                    b.HasIndex("TipoVinculoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("VinculosInstitucionais");
                });

            modelBuilder.Entity("SubTipoAtividade", b =>
                {
                    b.Property<int>("SubtipoAtividadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<int>("TipoAtividadeId")
                        .HasColumnType("int");

                    b.HasKey("SubtipoAtividadeId");

                    b.HasIndex("TipoAtividadeId");

                    b.ToTable("SubtiposAtividade");
                });

            modelBuilder.Entity("TipoAtividade", b =>
                {
                    b.Property<int>("TipoAtividadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("TipoAtividadeId");

                    b.ToTable("TiposAtividade");
                });

            modelBuilder.Entity("TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("TipoVinculo", b =>
                {
                    b.Property<int>("TipoVinculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TipoVinculoId");

                    b.ToTable("TiposVinculo");
                });

            modelBuilder.Entity("AtividadeAdministrativa", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithOne("AtividadeAdministrativa")
                        .HasForeignKey("AtividadeAdministrativa", "AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("AtividadeEnsino", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithOne("AtividadeEnsino")
                        .HasForeignKey("AtividadeEnsino", "AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("AtividadeExtensao", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithOne("AtividadeExtensao")
                        .HasForeignKey("AtividadeExtensao", "AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("AtividadePesquisa", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithOne("AtividadePesquisa")
                        .HasForeignKey("AtividadePesquisa", "AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Atividade", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.SolicitacaoProgressao", "SolicitacaoProgressao")
                        .WithMany("Atividades")
                        .HasForeignKey("SolicitacaoProgressaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubTipoAtividade", "SubTipoAtividade")
                        .WithMany()
                        .HasForeignKey("SubTipoAtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TipoAtividade", "TipoAtividade")
                        .WithMany()
                        .HasForeignKey("TipoAtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoProgressao");

                    b.Navigation("SubTipoAtividade");

                    b.Navigation("TipoAtividade");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Documento", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Atividade", "Atividade")
                        .WithMany("Documentos")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProgressoAcademico.Models.SolicitacaoProgressao", "SolicitacaoProgressao")
                        .WithMany("Documentos")
                        .HasForeignKey("SolicitacaoProgressaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("SolicitacaoProgressao");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SolicitacaoProgressao", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Nivel", "NivelDestino")
                        .WithMany("SolicitacoesComoDestino")
                        .HasForeignKey("NivelDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.Nivel", "NivelOrigem")
                        .WithMany("SolicitacoesComoOrigem")
                        .HasForeignKey("NivelOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.StatusSolicitacao", "StatusSolicitacao")
                        .WithMany("SolicitacaoProgressao")
                        .HasForeignKey("StatusSolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.TipoProgresso", "TipoProgresso")
                        .WithMany("SolicitacaoProgressao")
                        .HasForeignKey("TipoProgressoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.Usuario", "Usuario")
                        .WithMany("SolicitacaoProgressao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelDestino");

                    b.Navigation("NivelOrigem");

                    b.Navigation("StatusSolicitacao");

                    b.Navigation("TipoProgresso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.UsuarioPerfil", b =>
                {
                    b.HasOne("ProgressoAcademico.Models.Usuario", "Usuario")
                        .WithOne("UsuarioPerfil")
                        .HasForeignKey("ProgressoAcademico.Models.UsuarioPerfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.VinculoInstitucional", b =>
                {
                    b.HasOne("Instituicao", "Instituicao")
                        .WithMany("Vinculos")
                        .HasForeignKey("InstituicaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.Nivel", "Nivel")
                        .WithMany("VinculoInstitucionals")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TipoVinculo", "TipoVinculo")
                        .WithMany("VinculoInstitucional")
                        .HasForeignKey("TipoVinculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProgressoAcademico.Models.Usuario", "Usuario")
                        .WithMany("VinculosInstitucionais")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instituicao");

                    b.Navigation("Nivel");

                    b.Navigation("TipoVinculo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubTipoAtividade", b =>
                {
                    b.HasOne("TipoAtividade", "TipoAtividade")
                        .WithMany("Subtipos")
                        .HasForeignKey("TipoAtividadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoAtividade");
                });

            modelBuilder.Entity("Instituicao", b =>
                {
                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Atividade", b =>
                {
                    b.Navigation("AtividadeAdministrativa")
                        .IsRequired();

                    b.Navigation("AtividadeEnsino")
                        .IsRequired();

                    b.Navigation("AtividadeExtensao")
                        .IsRequired();

                    b.Navigation("AtividadePesquisa")
                        .IsRequired();

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Nivel", b =>
                {
                    b.Navigation("SolicitacoesComoDestino");

                    b.Navigation("SolicitacoesComoOrigem");

                    b.Navigation("VinculoInstitucionals");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.SolicitacaoProgressao", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.StatusSolicitacao", b =>
                {
                    b.Navigation("SolicitacaoProgressao");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.TipoProgresso", b =>
                {
                    b.Navigation("SolicitacaoProgressao");
                });

            modelBuilder.Entity("ProgressoAcademico.Models.Usuario", b =>
                {
                    b.Navigation("SolicitacaoProgressao");

                    b.Navigation("UsuarioPerfil")
                        .IsRequired();

                    b.Navigation("VinculosInstitucionais");
                });

            modelBuilder.Entity("TipoAtividade", b =>
                {
                    b.Navigation("Subtipos");
                });

            modelBuilder.Entity("TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("TipoVinculo", b =>
                {
                    b.Navigation("VinculoInstitucional");
                });
#pragma warning restore 612, 618
        }
    }
}
